version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
    build:
      commnads:
        - echo Building files
        - npm run build
        - rm -rf node_modules
artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: no